SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
UI_TOP_HEIGHT = 50
UI_FONT_SIZE = 40

LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 150
PLAYER_ACCELERATION = 500
PLAYER_LIVES = 3

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 1.2
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTERIOD_MAX_DENSITY = 0.05

SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

SCORE_MAX_PER_SECOND = 4
SCORE_PER_SPLIT = 10
